@baseUrl = http://localhost:8000
@token = none

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
###

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "username": "test",
    "password": "test",
    "phone": "123456789",
    "address": "test",
    "city": "test",
    "role": "admin"
}
###

### Get Member Info
GET {{baseUrl}}/api/auth/info
Content-Type: application/json
Authorization: Bearer {{token}}
###