@baseUrl = http://localhost:8000
@token = none

### Get Member List
GET {{baseUrl}}/api/members
Content-Type: application/json
### 

### Get Member Detail
GET {{baseUrl}}/api/members/10
Content-Type: application/json
### 

### Post Create Member
POST {{baseUrl}}/api/members/create
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "username": "test2",
    "password": "test",
    "phone": "08123456789",
    "is_active": "True",
    "role": "member",
    "email": "test@test.com"
}
### 

### Put Update Member
PUT {{baseUrl}}/api/members/update/10
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "phone": "08123456789",
    "is_active": "True",
    "role": "admin"
}
###

### Patch Update Member
PATCH {{baseUrl}}/api/members/update/10
Content-Type: application/json

{
    "password": "test"
}
###

### Delete Remove Member
DELETE {{baseUrl}}/api/members/delete/10
Content-Type: application/json
### 